name: Android Instrumentation Tests

on: [pull_request]

jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [32] # You can specify the API levels you want to test against
        target: [default] # [default, google_apis, google_apis_playstore]

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Download and set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          channel: 'stable'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up emulator
        run: |
          echo "Installing emulator"
          sudo $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "system-images;android-${{ matrix.api-level }};google_apis;x86_64"
          echo "Creating AVD"
          echo no | sudo $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;x86_64" --force
          sudo $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-window -no-audio -no-snapshot -netdelay none -netspeed full &
          sudo $ANDROID_SDK_ROOT/platform-tools/adb wait-for-device
          sudo $ANDROID_SDK_ROOT/platform-tools/adb shell settings put global window_animation_scale 0 &
          sudo $ANDROID_SDK_ROOT/platform-tools/adb shell settings put global transition_animation_scale 0 &
          sudo $ANDROID_SDK_ROOT/platform-tools/adb shell settings put global animator_duration_scale 0 &
          sleep 60  

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest

      - name: Run Jacoco Report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
